---
name: nessus-manager

releases:
  - name: nessus-manager
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-300000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

instance_groups:
  - name: nessus-manager
    instances: 1
    azs: [z1]
    networks:
      - name: default
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    jobs:
      - name: nessus-manager
        release: nessus-manager
        properties:
          nessus-manager:
            license: ((nessus_manager_license))
            username: ((nessus_manager_username))
            password: ((nessus_manager_password))

variables:
- name: nessus_manager_password
  type: password
